/* eslint-disable camelcase */
const csvWriter = require('csv-write-stream');
const fs = require('fs');

const writer = csvWriter();
writer.pipe(fs.createWriteStream('userTable.csv'));

const userTable = ['Robert',
  'Stannis',
  'Gendry',
  'Renly',
  'Brienne',
  'Melisandre',
  'Cersei',
  'Jaimie',
  'Tywin',
  'Tyrion',
  'Varys',
  'Tommen',
  'Bronn',
  'Petyr',
  'Joffrey',
  'Margaery',
  'Sandor',
  'Gregor',
  'Aegon',
  'Daenerys',
  'Drogo',
  'Arya',
  'Bran',
  'Jon',
  'Ned',
  'Sansa',
  'Robb',
  'Catelyn',
  'Asha',
  'Theon',
  'Ramsay',
  'Benjen',
  'Samwell',
  'Tormund',
  'Davos',
  'Eddard',
  'Ellaria',
  'Balon',
  'Jaqen',
  'Lyanna',
  'Jorah',
  'Nymeria',
  'Oberyn',
  'Osha',
  'Rhaegal',
  'Rickard',
  'Ghost',
  'Lady',
  'Edmure',
  'Walder',
  'Hodor',
  'Greywind',
  'Missandei',
  'Rickon',
  'Jeyne',
  'Roose',
  'Viserys',
  'Podrick',
  'Beric',
  'Ygritte',
];

const url = ['https://reviewmodulepics.s3-us-west-2.amazonaws.com/1.jpg',
  'https://reviewmodulepics.s3-us-west-2.amazonaws.com/2.jpg',
  'https://reviewmodulepics.s3-us-west-2.amazonaws.com/3.jpg',
  'https://reviewmodulepics.s3-us-west-2.amazonaws.com/4.jpg',
  'https://reviewmodulepics.s3-us-west-2.amazonaws.com/5.jpg',
  'https://reviewmodulepics.s3-us-west-2.amazonaws.com/6.jpg',
  'https://reviewmodulepics.s3-us-west-2.amazonaws.com/7.jpg',
  'https://reviewmodulepics.s3-us-west-2.amazonaws.com/8.jpg',
  'https://reviewmodulepics.s3-us-west-2.amazonaws.com/9.jpg',
  'https://reviewmodulepics.s3-us-west-2.amazonaws.com/10.jpg',
  'https://reviewmodulepics.s3-us-west-2.amazonaws.com/11.jpg',
  'https://reviewmodulepics.s3-us-west-2.amazonaws.com/12.jpg',
  'https://reviewmodulepics.s3-us-west-2.amazonaws.com/13.jpg',
  'https://reviewmodulepics.s3-us-west-2.amazonaws.com/14.jpg',
  'https://reviewmodulepics.s3-us-west-2.amazonaws.com/15.jpg',
  'https://reviewmodulepics.s3-us-west-2.amazonaws.com/16.jpg',
  'https://reviewmodulepics.s3-us-west-2.amazonaws.com/17.jpg',
  'https://reviewmodulepics.s3-us-west-2.amazonaws.com/18.jpg',
  'https://reviewmodulepics.s3-us-west-2.amazonaws.com/19.jpg',
  'https://reviewmodulepics.s3-us-west-2.amazonaws.com/20.jpg',
  'https://reviewmodulepics.s3-us-west-2.amazonaws.com/21.jpg',
  'https://reviewmodulepics.s3-us-west-2.amazonaws.com/22.jpg',
  'https://reviewmodulepics.s3-us-west-2.amazonaws.com/23.jpg',
  'https://reviewmodulepics.s3-us-west-2.amazonaws.com/24.jpg',
  'https://reviewmodulepics.s3-us-west-2.amazonaws.com/25.jpg',
  'https://reviewmodulepics.s3-us-west-2.amazonaws.com/26.jpg',
  'https://reviewmodulepics.s3-us-west-2.amazonaws.com/27.jpg',
  'https://reviewmodulepics.s3-us-west-2.amazonaws.com/28.jpg',
  'https://reviewmodulepics.s3-us-west-2.amazonaws.com/29.jpg',
  'https://reviewmodulepics.s3-us-west-2.amazonaws.com/30.jpg',
  'https://reviewmodulepics.s3-us-west-2.amazonaws.com/31.jpg',
  'https://reviewmodulepics.s3-us-west-2.amazonaws.com/32.jpg',
  'https://reviewmodulepics.s3-us-west-2.amazonaws.com/33.jpg',
  'https://reviewmodulepics.s3-us-west-2.amazonaws.com/34.jpg',
  'https://reviewmodulepics.s3-us-west-2.amazonaws.com/35.jpg',
  'https://reviewmodulepics.s3-us-west-2.amazonaws.com/36.jpg',
  'https://reviewmodulepics.s3-us-west-2.amazonaws.com/37.jpg',
  'https://reviewmodulepics.s3-us-west-2.amazonaws.com/38.jpg',
  'https://reviewmodulepics.s3-us-west-2.amazonaws.com/39.jpg',
  'https://reviewmodulepics.s3-us-west-2.amazonaws.com/40.jpg',
  'https://reviewmodulepics.s3-us-west-2.amazonaws.com/41.jpg',
  'https://reviewmodulepics.s3-us-west-2.amazonaws.com/42.jpg',
  'https://reviewmodulepics.s3-us-west-2.amazonaws.com/43.jpg',
  'https://reviewmodulepics.s3-us-west-2.amazonaws.com/44.jpg',
  'https://reviewmodulepics.s3-us-west-2.amazonaws.com/45.jpg',
  'https://reviewmodulepics.s3-us-west-2.amazonaws.com/46.jpg',
  'https://reviewmodulepics.s3-us-west-2.amazonaws.com/47.jpg',
  'https://reviewmodulepics.s3-us-west-2.amazonaws.com/48.jpg',
  'https://reviewmodulepics.s3-us-west-2.amazonaws.com/49.jpg',
  'https://reviewmodulepics.s3-us-west-2.amazonaws.com/50.jpg',
  'https://reviewmodulepics.s3-us-west-2.amazonaws.com/51.jpg',
  'https://reviewmodulepics.s3-us-west-2.amazonaws.com/52.jpg',
  'https://reviewmodulepics.s3-us-west-2.amazonaws.com/53.jpg',
  'https://reviewmodulepics.s3-us-west-2.amazonaws.com/54.jpg',
  'https://reviewmodulepics.s3-us-west-2.amazonaws.com/55.jpg',
  'https://reviewmodulepics.s3-us-west-2.amazonaws.com/56.jpg',
  'https://reviewmodulepics.s3-us-west-2.amazonaws.com/57.jpg',
  'https://reviewmodulepics.s3-us-west-2.amazonaws.com/58.jpg',
  'https://reviewmodulepics.s3-us-west-2.amazonaws.com/59.jpg',
  'https://reviewmodulepics.s3-us-west-2.amazonaws.com/60.jpg'];

for (let i = 0; i < 60; i += 1) {
  const id = i;
  const user_name = userTable[i];
  const avatar_url = url[i];

  writer.write({
    id,
    user_name,
    avatar_url,
  });
}

writer.end();
